name: Extract Boot Image

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM download URL'
        required: true
        default: 'https://mirrorbits.lineageos.org/full/tissot/20230321/lineage-19.1-20230321-nightly-tissot-signed.zip'

jobs:
  extract_boot_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip
          pip3 install adbutils
          echo "BUILD_sTIME=$(TZ=Asia/Shanghai date -d @$(date +%s) +'%Y_%m_%d-%H%M%S_%Z')" >> $GITHUB_ENV

      - name: Download ROM and extract boot image
        run: |
          cd ~
          git clone https://github.com/tosasitill/android_tools.git --depth=1
          cd android_tools
          chmod +x setup.sh
          sudo bash setup.sh
          cp -a ~/android_tools/tools/extractor.sh ~/android_tools/tools/Firmware_extractor
          wget -O 1.zip ${{ github.event.inputs.rom_url }}
          ./tools/rom_extract.sh 1.zip

      - name: 上传至 Github Releases
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "~/android_tools/dumps/1/*"
          tag: "BOOT_IMG"
          token: ${{ secrets.GITHUB_TOKEN }}

