name: MagiskPatchAction

on:
  workflow_dispatch:
    inputs:
      rom-url:
        description: 'ROM 下载直链'

jobs:
  MagiskPatchAction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 安装依赖文件
      run: |
        sudo apt update
        sudo apt install -y wget unzip binwalk curl
        
    - name: 下载 ROM 并提取 Payload.bin
      id: download-rom
      run: |
        url=${{ github.event.inputs.rom-url }}
        curl --silent --location --remote-name "$url"
        # Check if payload.bin exists, and convert it to zip format if necessary
        if [ -f payload.bin ]; then
          mkdir payload
          dd if=payload.bin of=payload.zip bs=1 skip=202
          unzip payload.zip -d payload/
          cd payload/
        fi
        # Extract zip file
        unzip *.zip

    - name: 下载 Magisk
      run: |
        git clone https://github.com/tosasitill/MagiskPatchActionEXTRA.git
        
    - name: 获取变量
      run: |
        echo "BUILD_TIME=$(date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV
        
    - name: 修补镜像
      run: |
        if [ -f init_boot.img ]; then
           chmod +x magisk.sh && ./boot_patch.sh ./init_boot.img
        else
           chmod +x magisk.sh && ./boot_patch.sh ./boot.img
        fi

    - name: 上传至 Github Releases
      uses: ncipollo/release-action@v1.12.0
      with:
          artifacts: "${{ github.workspace }}/new-boot.img"
          tag: "${{ env.BUILD_TIME }}"
          token: ${{ secrets.GITHUB_TOKEN }}
