name: MagiskPatchAction

on:
  workflow_dispatch:
    inputs:
      rom-url:
        description: 'ROM 下载直链'
        required: true
        default: 'https://mirrorbits.lineageos.org/full/tissot/20230214/lineage-19.1-20230214-nightly-tissot-signed.zip'
      CPU_TYPE:
        description: 'CPU type'
        required: false
      ANDROID_SDK:
        description: 'android sdk'
        required: true
        default: '32'
        
env:
  TZ: Asia/Shanghai
  Payload_Dumper_Go_Url: https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz
  
jobs:
  MagiskPatchAction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 安装依赖文件
      run: |
        sudo apt update
        sudo apt install -y wget unzip binwalk curl
        
    - name: 克隆 Payload 解包源代码
      run: |
       cd ~
       mkdir -p ~/payload_dumper_go
       wget -O payload_dumper_go.tar.gz $Payload_Dumper_Go_Url
       tar -C ~/payload_dumper_go/ -zxvf payload_dumper_go.tar.gz
       
    - name: 下载 ROM 并提取 boot.img/init_boot.img
      run: |
       cd ~
       wget -O rom.zip ${{ github.event.inputs.rom-url }}
       cd ~
       unzip rom.zip -d payload_dumper_go
       if [ -f payload.bin ]; then
          cd ~
          cd payload_dumper_go
          ./payload-dumper-go -o ~/payload_dumper_go -p boot payload.bin
          ./payload-dumper-go -o ~/payload_dumper_go -p init_boot payload.bin
        fi
    
    - name: 下载 Magisk
      run: |
        git clone https://github.com/tosasitill/MagiskPatchActionEXTRA.git
        cd MagiskPatchActionEXTRA/

        
    - name: 获取变量
      run: |
        echo "BUILD_TIME=$(date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV
        TYPE=${{ github.event.inputs.CPU_TYPE }}
        
    - name: 修补镜像
      run: |
        if [ -f init_boot.img ]; then
           ls
           sh ./boot_patch.sh '$HOME/payload_dumper_go/init_boot.img' 
        else
           sh ./boot_patch.sh '$HOME/payload_dumper_go/boot.img' 
        fi

    - name: 上传至 Github Releases
      uses: ncipollo/release-action@v1.12.0
      with:
          artifacts: "~/payload_dumper_go/MagiskPatchActionEXTRA/new-boot.img"
          tag: "${{ env.BUILD_TIME }}"
          token: ${{ secrets.GITHUB_TOKEN }}
