name: 提取 boot.img / init_boot.img

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true

jobs:
  extract_boot_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip
          apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename
          apt install liblzma-dev python-pip brotli lz4
          pip install backports.lzma protobuf pycrypto

      - name: 提取镜像
        run: |
          cd ~
          git clone --recurse-submodules https://github.com/tosasitill/Firmware_extractor.git
          cd Firmware_extractor
          wget ${{ github.event.inputs.rom_url }} -o firmware.zip
          ./extractor.sh firmware.zip
          touch build_info.txt
          cd out
          ls

      - name: 上传镜像
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "~/Firmware_extractor/out/*"
            tag: "Uploaded boot.img"
            bodyFile: "~/Firmware_extractor/build_info.txt"
            token: ${{ secrets.GITHUB_TOKEN }}

